name: CI

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Clone code on VM
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: 1.22.6

    - name: Install dependencies
      run: go mod download

    - name: Build project
      run: go build -v ./...